"""Markdown report renderers for pathdog results."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ._helpers import (
    _display_name, _edge_commands, _node_flags, _path_yields_dcsync,
)

if TYPE_CHECKING:
    import networkx as nx

    from ..findings import Finding
    from ..pathfinder import PathResult
    from ..quickwins import QuickWin


def _stats_md_lines(stats: dict) -> list[str]:
    lines = [
        "## Graph Statistics\n",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total nodes | {stats['total_nodes']} |",
        f"| Total edges | {stats['total_edges']} |",
        f"| Pruned nodes (reachable) | {stats['pruned_nodes']} |",
        f"| Pruned edges | {stats['pruned_edges']} |",
        f"| Node reduction | {stats['reduction_pct']}% |",
        "",
    ]
    return lines


def render_markdown(
    paths: list["PathResult"],
    G: "nx.DiGraph",
    source: str,
    target: str,
    stats: dict | None = None,
    intermediate: list[dict] | None = None,
    quickwins: dict[str, list["QuickWin"]] | None = None,
    pivots: list[dict] | None = None,
    findings: list["Finding"] | None = None,
) -> str:
    lines: list[str] = []
    lines.append("# Pathdog — Attack Path Report\n")
    lines.append(f"**Source:** `{_display_name(G, source)}`  ")
    lines.append(f"**Target:** `{_display_name(G, target)}`\n")

    if stats:
        lines.extend(_stats_md_lines(stats))

    if not paths:
        lines.append(
            f"> **No path found** from `{_display_name(G, source)}` to "
            f"`{_display_name(G, target)}`.  \n"
            "> The owned user may not have any edges leading to DA in this dump."
        )
        if intermediate:
            lines.extend(_intermediate_md(G, source, intermediate))
        if pivots:
            lines.extend(_pivots_md(G, pivots))
        if quickwins:
            lines.extend(_quickwins_md(quickwins))
        if findings:
            lines.extend(_findings_md(findings))
        lines.append("\n---")
        lines.append("*Generated by [pathdog](https://github.com/dikabraxis/pathdog)*")
        return "\n".join(lines)

    lines.append(f"## Paths Found: {len(paths)}\n")

    for i, path in enumerate(paths, 1):
        lines.append(f"### Path {i} — Weight: {path.total_weight} | Hops: {path.hops}\n")

        # ASCII chain (with property flags)
        lines.append("```")
        first_flags = _node_flags(G, path.nodes[0])
        first_str = _display_name(G, path.nodes[0])
        if first_flags:
            first_str += f"  ⚑ {', '.join(first_flags)}"
        lines.append(first_str)
        for edge in path.edges:
            rel = edge["relation"]
            dst_name = _display_name(G, edge["dst"])
            dst_flags = _node_flags(G, edge["dst"])
            tail = f"  ⚑ {', '.join(dst_flags)}" if dst_flags else ""
            arrow = f"  └─[{rel}]"
            pad = max(1, 42 - len(arrow))
            lines.append(f"{arrow}{'─' * pad}► {dst_name}{tail}")
        lines.append("```\n")

        if _path_yields_dcsync(G, path):
            lines.append(
                "> ✦ **DCSync acquired** — once `dacledit` lands, "
                "`secretsdump` returns every domain hash (incl. krbtgt → Golden Ticket).\n"
            )

        # Edge table
        lines.append("| # | From | Relation | To | Weight |")
        lines.append("|---|------|----------|----|--------|")
        for j, edge in enumerate(path.edges, 1):
            lines.append(
                f"| {j} "
                f"| `{_display_name(G, edge['src'])}` "
                f"| **{edge['relation']}** "
                f"| `{_display_name(G, edge['dst'])}` "
                f"| {edge['weight']} |"
            )
        lines.append("")

        # Per-hop exploit steps with actor tracking
        lines.append("#### Exploit steps\n")
        actor = _display_name(G, path.nodes[0])
        for j, edge in enumerate(path.edges, 1):
            cmd, next_actor = _edge_commands(G, edge, actor)
            src_label = _display_name(G, edge["src"])
            dst_label = _display_name(G, edge["dst"])
            lines.append(f"**Hop {j} — [{edge['relation']}]** `{src_label}` → `{dst_label}`\n")
            lines.append(f"> *Operating as: `{actor}`*  ")
            lines.append(f"> {cmd.description}\n")
            if cmd.has_commands:
                lines.append("```bash")
                lines.extend(cmd.commands)
                lines.append("```\n")
            if next_actor != actor:
                lines.append(f"> ✦ **Identity obtained: `{next_actor}`**\n")
            actor = next_actor

    if pivots:
        lines.extend(_pivots_md(G, pivots))

    if quickwins:
        lines.extend(_quickwins_md(quickwins))
    if findings:
        lines.extend(_findings_md(findings))

    lines.append("---")
    lines.append("*Generated by [pathdog](https://github.com/dikabraxis/pathdog)*")
    return "\n".join(lines)


def _intermediate_md(
    G: "nx.DiGraph", source: str, suggestions: list[dict]
) -> list[str]:
    lines: list[str] = ["\n## Intermediate targets reachable\n",
                        "When DA isn't directly reachable, pivot through these:\n",
                        "| # | Score | Target | Kind | Hops | Flags |",
                        "|---|-------|--------|------|------|-------|"]
    for i, s in enumerate(suggestions, 1):
        nid = s["node"]
        path = s["path"]
        score = s["score"]
        flags = ", ".join(_node_flags(G, nid)) or "—"
        hops = path.hops if path else "?"
        lines.append(
            f"| {i} | {score} | `{_display_name(G, nid)}` "
            f"| {G.nodes[nid].get('kind', '?')} | {hops} | {flags} |"
        )
    lines.append("")
    for i, s in enumerate(suggestions, 1):
        path = s["path"]
        if not path:
            continue
        chain = " → ".join(f"`{_display_name(G, n)}`" for n in path.nodes)
        lines.append(f"**{i}.** {chain}\n")
    return lines


def _quickwins_md(quickwins: dict[str, list["QuickWin"]]) -> list[str]:
    lines: list[str] = ["\n## Domain-wide quick wins\n",
                        "Surfaced from BloodHound node properties — independent of any owned user.\n"]
    for cat in sorted(quickwins):
        items = quickwins[cat]
        lines.append(f"### {cat} — {len(items)} candidate(s)\n")
        for qw in items:
            lines.append(f"- **`{qw.node_name}`** ({qw.node_kind}) — {qw.detail}")
            if qw.commands:
                lines.append("  ```bash")
                for c in qw.commands:
                    lines.append(f"  {c}")
                lines.append("  ```")
        lines.append("")
    return lines


def _findings_md(findings: list["Finding"]) -> list[str]:
    def cell(value: object) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = [
        "\n## Prioritized findings\n",
        "| Severity | Category | Finding | Evidence |",
        "|----------|----------|---------|----------|",
    ]
    for finding in findings:
        lines.append(
            f"| {finding.severity} | {cell(finding.category)} | "
            f"`{cell(finding.title)}` | {cell(finding.evidence)} |"
        )
    lines.append("")
    return lines


def _pivots_md(G: "nx.DiGraph", pivots: list[dict]) -> list[str]:
    if not pivots:
        return []
    lines = [
        "\n## Pivot candidates (have a path to DA, attackable out-of-band)\n",
        "Compromise any of these via the listed vector and the existing graph path takes you to DA.\n",
        "| # | Score | Pivot | Hops to DA | Vectors | Flags |",
        "|---|-------|-------|------------|---------|-------|",
    ]
    for i, pv in enumerate(pivots, 1):
        nid = pv["node"]
        ptd = pv["path_to_da"]
        flags = ", ".join(_node_flags(G, nid)) or "—"
        hops = ptd.hops if ptd else "?"
        vectors = ", ".join(pv["vectors"])
        lines.append(
            f"| {i} | {pv['score']} | `{_display_name(G, nid)}` | {hops} | {vectors} | {flags} |"
        )
    lines.append("")
    for i, pv in enumerate(pivots, 1):
        nid = pv["node"]
        ptd = pv["path_to_da"]
        lines.append(f"### {i}. `{_display_name(G, nid)}`\n")
        if pv["vector_commands"]:
            lines.append("```bash")
            lines.extend(pv["vector_commands"])
            lines.append("```\n")
        if ptd:
            chain = " → ".join(f"`{_display_name(G, n)}`" for n in ptd.nodes)
            lines.append(f"**Onward path to DA:** {chain}\n")
    return lines


def render_markdown_multi(
    results: list[tuple[str, list]],
    G: "nx.DiGraph",
    target: str,
    stats: dict | None = None,
    intermediates: dict[str, list[dict]] | None = None,
    quickwins: dict[str, list["QuickWin"]] | None = None,
    pivots: list[dict] | None = None,
    findings: list["Finding"] | None = None,
) -> str:
    intermediates = intermediates or {}
    if len(results) == 1:
        source, paths = results[0]
        return render_markdown(
            paths, G, source, target, stats,
            intermediate=intermediates.get(source),
            quickwins=quickwins,
            pivots=pivots,
            findings=findings,
        )

    lines: list[str] = []
    if results:
        lines.append("# Pathdog — Multi-User Attack Path Report\n")
        lines.append(f"**Target:** `{_display_name(G, target)}`\n")
    else:
        lines.append("# Pathdog — Triage Report\n")
        if target:
            lines.append(f"**Target context:** `{_display_name(G, target)}`\n")
        else:
            lines.append("**Target context:** `global`\n")
    if stats:
        lines.extend(_stats_md_lines(stats))

    for source, paths in results:
        src_label = _display_name(G, source)
        lines.append(f"\n---\n\n## Owned: `{src_label}`\n")
        single = render_markdown(
            paths, G, source, target, stats=None,
            intermediate=intermediates.get(source),
            quickwins=None,
            pivots=None,
        )
        lines.append("\n".join(single.split("\n")[3:]))

    if pivots:
        lines.append("\n---\n")
        lines.extend(_pivots_md(G, pivots))

    if quickwins:
        lines.append("\n---\n")
        lines.extend(_quickwins_md(quickwins))
    if findings:
        lines.append("\n---\n")
        lines.extend(_findings_md(findings))

    return "\n".join(lines)


def render_markdown_node_visibility(
    G: "nx.DiGraph",
    node: str,
    target: str | None,
    outbound_paths: list,
    outbound_intermediate: list[dict],
    inbound_sources: list[dict],
    stats: dict | None = None,
    outbound_control: list[dict] | None = None,
    inbound_control: list[dict] | None = None,
) -> str:
    """Render a Markdown report for outbound/inbound node visibility."""
    node_label = _display_name(G, node)
    tgt_label = _display_name(G, target) if target else "high-value targets"
    flags = _node_flags(G, node)
    outbound_control = outbound_control or []
    inbound_control = inbound_control or []

    lines: list[str] = []
    lines.append(f"# Pathdog — Node Visibility: `{node_label}`\n")
    if flags:
        lines.append(f"**Flags:** {', '.join(flags)}\n")
    if stats:
        lines.extend(_stats_md_lines(stats))

    # ── Outbound object control ───────────────────────────────────────────────
    direct_count = sum(1 for e in outbound_control if e["via_group"] is None)
    lines.append(f"## → Outbound Object Control ({direct_count} direct, "
                 f"{len(outbound_control) - direct_count} via group)\n")
    if outbound_control:
        lines.append("| Relation | Target | How |")
        lines.append("|----------|--------|-----|")
        for e in outbound_control:
            via = f"via {e['via_group']}" if e["via_group"] else "direct"
            lines.append(
                f"| **{e['relation']}** "
                f"| `{_display_name(G, e['dst'])}` "
                f"| {via} |"
            )
        lines.append("")
    else:
        lines.append("> No outbound privileges found.\n")

    # ── Inbound object control ────────────────────────────────────────────────
    lines.append(f"## ← Inbound Object Control ({len(inbound_control)} principal(s))\n")
    if inbound_control:
        lines.append("| Relation | Principal |")
        lines.append("|----------|-----------|")
        for e in inbound_control:
            lines.append(
                f"| **{e['relation']}** "
                f"| `{_display_name(G, e['src'])}` |"
            )
        lines.append("")
    else:
        lines.append("> No inbound privileges found.\n")

    # ── Attack paths (outbound) ───────────────────────────────────────────────
    lines.append(f"## → Attack Paths — outbound to `{tgt_label}`\n")
    if outbound_paths:
        for i, path in enumerate(outbound_paths, 1):
            lines.append(f"### Path {i} — Weight: {path.total_weight} | Hops: {path.hops}\n")
            lines.append("```")
            first_flags = _node_flags(G, path.nodes[0])
            first_str = _display_name(G, path.nodes[0])
            if first_flags:
                first_str += f"  ⚑ {', '.join(first_flags)}"
            lines.append(first_str)
            for edge in path.edges:
                rel = edge["relation"]
                dst_name = _display_name(G, edge["dst"])
                dst_flags = _node_flags(G, edge["dst"])
                tail = f"  ⚑ {', '.join(dst_flags)}" if dst_flags else ""
                arrow = f"  └─[{rel}]"
                pad = max(1, 42 - len(arrow))
                lines.append(f"{arrow}{'─' * pad}► {dst_name}{tail}")
            lines.append("```\n")
            if _path_yields_dcsync(G, path):
                lines.append("> ✦ **DCSync acquired**\n")
            actor = _display_name(G, path.nodes[0])
            for j, edge in enumerate(path.edges, 1):
                if edge["relation"] in ("MemberOf", "Contains"):
                    continue
                cmd, next_actor = _edge_commands(G, edge, actor)
                src_l = _display_name(G, edge["src"])
                dst_l = _display_name(G, edge["dst"])
                lines.append(f"**Hop {j} — [{edge['relation']}]** `{src_l}` → `{dst_l}`\n")
                lines.append(f"> *Operating as: `{actor}`*  ")
                lines.append(f"> {cmd.description}\n")
                if cmd.has_commands:
                    lines.append("```bash")
                    lines.extend(cmd.commands)
                    lines.append("```\n")
                if next_actor != actor:
                    lines.append(f"> ✦ **Identity obtained: `{next_actor}`**\n")
                actor = next_actor
        if outbound_intermediate:
            lines.extend(_intermediate_md(G, node, outbound_intermediate))
    elif outbound_intermediate:
        lines.extend(_intermediate_md(G, node, outbound_intermediate))
    else:
        lines.append("> No outbound paths to high-value targets found.\n")

    # ── Inbound attackers (full paths) ────────────────────────────────────────
    lines.append(f"## ← Inbound Attackers — who can reach `{node_label}`\n")
    if inbound_sources:
        lines.append(f"{len(inbound_sources)} principal(s) have an attack path to this node.\n")
        lines.append("| # | Score | Principal | Kind | Hops | Flags |")
        lines.append("|---|-------|-----------|------|------|-------|")
        for i, s in enumerate(inbound_sources, 1):
            nid = s["node"]
            path = s["path"]
            flags_s = ", ".join(_node_flags(G, nid)) or "—"
            hops = path.hops if path else "?"
            lines.append(
                f"| {i} | {s['score']} | `{_display_name(G, nid)}` "
                f"| {G.nodes[nid].get('kind', '?')} | {hops} | {flags_s} |"
            )
        lines.append("")
        for i, s in enumerate(inbound_sources, 1):
            path = s["path"]
            if not path:
                continue
            chain = " → ".join(f"`{_display_name(G, n)}`" for n in path.nodes)
            lines.append(f"**{i}.** {chain}\n")
    else:
        lines.append("> No paths found from other principals.\n")

    lines.append("---")
    lines.append("*Generated by [pathdog](https://github.com/dikabraxis/pathdog)*")
    return "\n".join(lines)
