EDGE_WEIGHTS = {
    "MemberOf": 1,
    "GenericAll": 2,
    "DCSync": 2,
    "GetChangesAll": 2,
    "AllExtendedRights": 2,
    "AddMember": 2,
    "ReadLAPSPassword": 2,
    "WriteDacl": 3,
    "WriteOwner": 3,
    "GenericWrite": 3,
    "Owns": 3,
    "ForceChangePassword": 3,
    "Contains": 1,
    "GPLink": 2,
    "AllowedToDelegate": 4,
    "AllowedToAct": 5,
    "HasSession": 4,
    "AdminTo": 2,
    "CanRDP": 3,
    "CanPSRemote": 3,
    "ExecuteDCOM": 3,
    "SQLAdmin": 3,
    "AddSelf": 2,
    "WriteAccountRestrictions": 4,
    "SyncLAPSPassword": 2,
    "AddKeyCredentialLink": 4,
    "WriteSPN": 3,
    "TrustedBy": 3,
}

DEFAULT_WEIGHT = 5
